name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 7 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
            scala: 2
          - java: 8
            scala: 3
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.${{ matrix.java }}"
    - uses: coursier/cache-action@v6
    - run: sbt -v
           $(if [[ "${{ matrix.scala }}" == "3" ]]; then echo SetScala3; fi)
           "project rootJVM"
           update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
