name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        pipeline: [true, false]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
      with:
        java-version: 17
        distribution: adopt
    - run: ./sbt -v
           -Dscalaz.pipeline=${{ matrix.pipeline }}
           "project rootJVM"
           "show usePipelining"
           update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
           clean update Test/compile
