name: CI
on:
  push:
jobs:
  wasm:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
      with:
        java-version: 21
        distribution: adopt
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - uses: coursier/cache-action@v6
    - run: ./sbt -v
           -Dscala_js_wasm
           "project exampleJS"
           allMainSize
    - run: git clean -fdx
    - run: ./sbt -v
           "project exampleJS"
           allMainSize
