name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 7 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
      with:
        java-version: 21
        distribution: adopt
    - run: ./sbt -v
           "project coreJVM"
           '++ 3.6.3!'
           update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
           clean update compile
