name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 7 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        scala:
        - "2.13.15"
        - "3.3.4"
        - "3.5.2"
        - "3.6.2-RC1"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
      with:
        java-version: 21
        distribution: adopt
    - uses: coursier/cache-action@v6
    - run: ./sbt -v
           "++ ${{ matrix.scala }}!"
           "project coreJVM"
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile clean
           update compile
